#+title: ranger-rclone-copy

Ranger Plugin to easily copy or move files to a remote location with rclone.

* Usage

#+begin_src
:rclone <command> <rclone-target> <dir>
#+end_src

Available ~<commands>~ are:

- ~copy~ :: https://rclone.org/commands/rclone_copy/
- ~copyto~ :: https://rclone.org/commands/rclone_copyto/
- ~move~ :: https://rclone.org/commands/rclone_move/
- ~moveto~ :: https://rclone.org/commands/rclone_moveto/

~<rclone-target>~ can be either a destination as you would provide to ~rclone copy~
directly or the key of a bookmarked destination.

~<dir>~ is an _optional_ argument that is appended to ~<rclone-target>~ after bookmark
resolution. This is useful to specify a subdirectory of a bookmark as
destination.

Tab completion for ~<command>~ and ~<rclone-target>~ (from bookmarks) is implemented.

** Bookmarks

Bookmarked destinations are a pair of a key and a destination.

- add a bookmark :: ~:add_rclone_target <key> <target>~
- remove a bookmark :: ~:remove_rclone_target <key>~
- change target to existing key :: ~:change_rclone_target <key> <new-target>~

The bookmarked targets are stored in a file in the ranger config directory that
is automatically created when a bookmark is added for the first time.


* Dependencies

- [[https://github.com/ranger/ranger][ranger]]
- [[https://rclone.org/][rclone]]

* Installation

#+begin_src
cd ~/.config/ranger/plugins
git clone https://github.com/einsiedlerspiel/ranger-rclone-copy.git
#+end_src
