#+title: ranger-rclone-copy

Ranger Plugin to easily copy files to a remote location via the rclone copy command.

* Usage

Use ~:rclone_copy <rclone-target>~ to copy the marked files in the current working
directory to ~<rclone-target>~. The command behaves like [[https://rclone.org/commands/rclone_copy][rclone copy.]]
~<rclone-target>~ can be either a destination as you would provide to ~rclone copy~
directly or the key of a bookmarked destination.

Bookmarked destinations are a pair of a key and a destination. Bookmarks can be
defined via ~:add_rclone_target <key> <target>~, removed via ~:remove_rclone_target
<key>~ and the target to a key can be changed with ~:change_rclone_target <key>
<new-target>~.

The bookmarked targets are stored in a file in the ranger config directory that
is automatically created when a bookmark is added for the first time.

~:rclone_copy~ has rudimentary tab completion for bookmarked targets.

* Dependencies

- [[https://github.com/ranger/ranger][ranger]]
- [[https://rclone.org/][rclone]]

* Installation

#+begin_src
cd ~/.config/ranger/plugins
git clone https://github.com/einsiedlerspiel/ranger-rclone-copy.git
#+end_src
